### ISSUE TITLE
Socket path access control check bug

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [yaakov123/hagana#10]
I believe that the filesystem access control logic implementation breaks in case of file descriptors:

```
import fs from 'fs';
import path from 'path';

export function run () {
  const filePath = path.resolve('./my-file');
  const socket = fs.openSync(filePath, 'w+');
  fs.writeFileSync(socket, 'Hello World!', { encoding: 'utf8' });
}
```

throws the following exception:

```
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type number (20)
    at new NodeError (node:internal/errors:388:5)
    at validateString (node:internal/validators:114:11)
    at Object.relative (node:path:1192:5)
    at We (/my/project/folder/node_modules/@hagana/hagana/dist/hagana.js:9:4219)
    at zr (/my/project/folder/node_modules/@hagana/hagana/dist/hagana.js:9:4332)
    at X (/my/project/folder/node_modules/@hagana/hagana/dist/hagana.js:9:4407)
    at Object.ae [as apply] (/my/project/folder/node_modules/@hagana/hagana/dist/hagana.js:22:742)
    at run (file:///my/project/folder/libs/lib-fs3.js:7:6)
    at file:///my/project/folder/src/index.js:11:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by yaakov123** [comment]
Alright, I'm probably going to have to maintain a map between file descriptors and their underlying file paths to deal with this one.
