### ISSUE TITLE
@yaakov123 Careful, your fix in `0.0.14` broke importing the `worker_thread` core module all together for me on Node.js v14:

### ISSUE THREAD

**Issue by yaakov123** [yaakov123/hagana#9]
@yaakov123 Careful, your fix in `0.0.14` broke importing the `worker_thread` core module all together for me on Node.js v14:

```
internal/modules/cjs/loader.js:889
  const err = new Error(message);
              ^

Error: Cannot find module 'node:worker_threads'
Require stack:
- /my/folder/test-hagana/node_modules/@hagana/hagana/dist/hagana.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/my/folder/test-hagana/node_modules/@hagana/hagana/dist/hagana.js:22:2482)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/my/folder/test-hagana/node_modules/@hagana/hagana/dist/hagana.js'
  ]
}
```

_Originally posted by @Mickael-van-der-Beek in https://github.com/yaakov123/hagana/issues/2#issuecomment-1165656882_

**Comment by yaakov123** [comment]
This isn't happening to me, do you have a repo that reproduces this behavior?

**Comment by Mickael-van-der-Beek** [comment]
@yaakov123 Sure, in my case, simply importing `hagana@^0.0.14` on `node@14.17.4` with an Apple M1 with OSX `Darwin Kernel Version 20.4.0` will crash with the stack trace I posted.

**Comment by Mickael-van-der-Beek** [comment]
I tested it out in `node@18.4.0` and it works fine so I guess it's purely a question of Node.js version and ESM vs. CJS module loaders for some reason.
